name: On release published

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release_published]

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: Real-MullaC/WinUtil-Docs
          ref: main

      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
